### ISSUE TITLE
Versión de UI inválida (1). La versión indicada ya no está disponible

### ISSUE THREAD

**Issue by adrianbarabino** [epagos/api_php#1]
Al intentar enviar el pago, en ambas modalidades (iframe y post) devuelve el error: Versión de UI inválida (1). La versión indicada ya no está disponible
![imagen_2024-09-30_225452185](https://github.com/user-attachments/assets/3b630645-6f01-4f5a-9ba1-6bf996cd2b5f)

**Comment by asalgueiro** [comment]
Hola, buenas tardes. Este problema no es de la API ni del SDK, sino de la configuración del organismo en el ambiente en que te lo devuelva. Deberías contactarte con el equipo de implementaciones (implementaciones@epagos.com.ar) para que ajusten ese configuración. Saludos
